name: books_rater
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth:
  cloud_firestore:
  firebase_core:
  flutter_riverpod:
  riverpod_annotation:
  freezed_annotation:
  image_picker:
  firebase_storage:
  intl:
  cloud_functions: ^4.6.5
  url_launcher:



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator:
  freezed:
  build_runner:
  json_serializable:

flutter:

  uses-material-design: true
